version: '3'

services:
  app:
    build: .
    container_name: microservices
    depends_on: 
      - zookeeper
      - kafka
    entrypoint: ./docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    image: postgres
    container_name: microservices-db
    restart: always
    user: postgres
    ports: 
      - "5432:5432"
    volumes: 
      - microservices-nestjs-db:/var/lib/postgres
    environment: 
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: microservices-db
      TZ: GMT
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-microservices  
    ports: 
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    container_name: microservices-kafka
    depends_on: 
      - zookeeper
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "create:1:1,find-all:1:1"


      
volumes: 
  microservices-nestjs-db:
    external: true
